package com.myspace.multiprocess;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FlowActions implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean enable_milestone_1;
	private java.lang.Boolean enable_milestone_2;
	private java.lang.Boolean enable_milestone_3;
	private java.util.List<java.lang.String> expected_signal_list;

	private java.lang.String selected_flow;

	private java.util.List<java.lang.String> start_signal_list;

	public FlowActions() {
	}

	public java.lang.Boolean getEnable_milestone_1() {
		return this.enable_milestone_1;
	}

	public void setEnable_milestone_1(java.lang.Boolean enable_milestone_1) {
		this.enable_milestone_1 = enable_milestone_1;
	}

	public java.lang.Boolean getEnable_milestone_2() {
		return this.enable_milestone_2;
	}

	public void setEnable_milestone_2(java.lang.Boolean enable_milestone_2) {
		this.enable_milestone_2 = enable_milestone_2;
	}

	public java.lang.Boolean getEnable_milestone_3() {
		return this.enable_milestone_3;
	}

	public void setEnable_milestone_3(java.lang.Boolean enable_milestone_3) {
		this.enable_milestone_3 = enable_milestone_3;
	}

	public java.util.List<java.lang.String> getExpected_signal_list() {
		return this.expected_signal_list;
	}

	public void setExpected_signal_list(
			java.util.List<java.lang.String> expected_signal_list) {
		this.expected_signal_list = expected_signal_list;
	}

	public java.lang.String getSelected_flow() {
		return this.selected_flow;
	}

	public void setSelected_flow(java.lang.String selected_flow) {
		this.selected_flow = selected_flow;
	}

	public java.util.List<java.lang.String> getStart_signal_list() {
		return this.start_signal_list;
	}

	public void setStart_signal_list(
			java.util.List<java.lang.String> start_signal_list) {
		this.start_signal_list = start_signal_list;
	}

	public FlowActions(java.lang.Boolean enable_milestone_1,
			java.lang.Boolean enable_milestone_2,
			java.lang.Boolean enable_milestone_3,
			java.util.List<java.lang.String> expected_signal_list,
			java.lang.String selected_flow,
			java.util.List<java.lang.String> start_signal_list) {
		this.enable_milestone_1 = enable_milestone_1;
		this.enable_milestone_2 = enable_milestone_2;
		this.enable_milestone_3 = enable_milestone_3;
		this.expected_signal_list = expected_signal_list;
		this.selected_flow = selected_flow;
		this.start_signal_list = start_signal_list;
	}

}